modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "zps"
version = "${version}"
displayName = "Zero Point Systems"
authors = "G_Mungus"
description = '''
Advanced solutions delivering unmatched efficiency and flexibility.
'''
logoFile = "assets/zps/icon.png"

[[dependencies.zps]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
