modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "zps"
version = "${version}"
displayName = "Zero Point Systems"
authors = "G_Mungus"
description = '''
Advanced solutions delivering unmatched efficiency and flexibility.
'''
logoFile = "assets/zps/icon.png"

[[dependencies.zps]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zps]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "zps.mixins.json"
