modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "zps"
version = "${version}"
displayName = "Zero Point Systems"
authors = "G_Mungus, Quoissant, Cosmos, PacificCyan"
description = '''
Advanced solutions delivering unmatched efficiency and flexibility.
'''
logoFile = "assets/zps/icon.png"

[[mixins]]
config = "zps.mixins.json"

[[dependencies.zps]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zps]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zps]]
modId = "radios"
type = "required"
versionRange = "[1.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zps]]
modId = "fusion"
type = "required"
versionRange = "[1.1.1a,)"
ordering = "NONE"
side = "CLIENT"
